#include "spwm_core.h"

// ==============================================================================
// Function: SPWM_Init
// Purpose: Validates pointers, maps 120-degree phases, and pre-computes safety limits.
// ==============================================================================
int8_t SPWM_Init(SPWM_Handle_t *hspwm, const int16_t *lut, uint32_t arr_val, 
                 uint32_t igbt_min_ticks, uint32_t dead_time_ticks) {
    
    // Pointer validation to prevent runtime HardFaults
    if (!hspwm || !lut || !hspwm->CCR1_Reg || !hspwm->CCR2_Reg || !hspwm->CCR3_Reg) {
        return -1; 
    }
    
    hspwm->sine_table = lut;
    hspwm->timer_arr = arr_val;
    
    // Pre-calculate baseline virtual zero (50% duty cycle point)
    hspwm->timer_center = arr_val >> 1;
    
    // The pulse generated by the timer must be wider than the IGBT minimum threshold
    // by exactly the duration of the hardware dead-time to survive the rising edge delay
    uint32_t safe_pulse_ticks = igbt_min_ticks + dead_time_ticks;
    
    // In Center-Aligned mode, the physical pulse width is twice the CCR register value.
    // Thus, the CCR boundary is exactly half the total safe pulse width.
    hspwm->ccr_min_limit = safe_pulse_ticks >> 1;
    
    // Bootstrap Protection: ccr_max_limit ensures the low-side switch conducts
    // for at least safe_pulse_ticks per cycle to maintain the high-side bootstrap charge.
    hspwm->ccr_max_limit = arr_val - hspwm->ccr_min_limit;
    
    hspwm->duty_scale_q16 = 0; 
    hspwm->phase_step = 0; 

    // 120-degree phase separation mapped into a 32-bit integer phase space
    // Phase U: 0 degrees
    // Phase V: 120 degrees = (0xFFFFFFFF / 3) = 1431655765
    // Phase W: 240 degrees = (0xFFFFFFFF / 3) * 2 = 2863311530
    hspwm->phase_acc_u = 0;
    hspwm->phase_acc_v = 1431655765;
    hspwm->phase_acc_w = 2863311530; 
    
    hspwm->is_initialized = 1;
    return 0; 
}

// ==============================================================================
// Function: SPWM_Set_Frequency
// Purpose: Calculates the 32-bit DDS tuning word for fundamental frequency generation.
// Formula: Phase_Step = (Target_Frequency / Switching_Frequency) * 2^32
// ==============================================================================
void SPWM_Set_Frequency(SPWM_Handle_t *hspwm, float target_hz, float f_sw) {
    if (!hspwm->is_initialized) return;
    
    // High-precision floating point calculation outside the ISR to avoid truncation
    double step = ((double)target_hz / (double)f_sw) * 4294967296.0; 
    hspwm->phase_step = (uint32_t)step;
}

// ==============================================================================
// Function: SPWM_Set_Amplitude
// Purpose: Pre-computes the Q16 fixed-point scaling factor to prevent ISR math overflow.
// Formula: duty_scale_q16 = (amplitude_percent * timer_center * 65536) / (32767 * 100)
// ==============================================================================
void SPWM_Set_Amplitude(SPWM_Handle_t *hspwm, uint16_t amplitude_percent) {
    if (!hspwm->is_initialized) return;
    
    // Enforce pure SPWM limit to prevent harmonic overmodulation
    if (amplitude_percent > 100) {
        amplitude_percent = 100;
    }
    
    // 64-bit integer arithmetic ensures no intermediate overflow occurs during scaling
    uint64_t center = (uint64_t)hspwm->timer_center;
    hspwm->duty_scale_q16 = (uint32_t)((amplitude_percent * center * 65536ULL) / 3276700ULL);
}

// ==============================================================================
// Function: SPWM_Update_ISR
// Purpose: Executes non-blocking duty cycle computation with Bootstrap-safe clamping.
// MUST be called directly from the Timer Update Interrupt Service Routine (ISR).
// ==============================================================================
void SPWM_Update_ISR(SPWM_Handle_t *hspwm) {
    
    if (!hspwm->is_initialized) return;
    
    // 1. Advance the 32-bit phase accumulators
    // Hardware rollover at 2^32 provides natural, continuous 360-degree wrapping
    hspwm->phase_acc_u += hspwm->phase_step;
    hspwm->phase_acc_v += hspwm->phase_step;
    hspwm->phase_acc_w += hspwm->phase_step;
    
    // 2. Extract 8 Most Significant Bits (MSB) to index the 256-point LUT
    uint16_t idx_u = hspwm->phase_acc_u >> 24;
    uint16_t idx_v = hspwm->phase_acc_v >> 24;
    uint16_t idx_w = hspwm->phase_acc_w >> 24;
    
    // 3. Retrieve pure signed sine values (-32767 to +32767)
    int32_t val_u = hspwm->sine_table[idx_u];
    int32_t val_v = hspwm->sine_table[idx_v];
    int32_t val_w = hspwm->sine_table[idx_w];
    
    // 4. Compute Duty Cycles using Q16 DSP arithmetic
    // Division by 65536 replaces logical shifts to avoid implementation-defined signed operations (MISRA C)
    int32_t duty_u = (int32_t)hspwm->timer_center + ((val_u * (int32_t)hspwm->duty_scale_q16) / 65536);
    int32_t duty_v = (int32_t)hspwm->timer_center + ((val_v * (int32_t)hspwm->duty_scale_q16) / 65536);
    int32_t duty_w = (int32_t)hspwm->timer_center + ((val_w * (int32_t)hspwm->duty_scale_q16) / 65536);
    
    // 5. Pulse Dropping and Bootstrap Undervoltage Protection
    // Drops narrow pulses to 0% to prevent linear-region IGBT heating
    // Clamps high peaks strictly to ccr_max_limit to ensure bootstrap capacitor recharge
    if (duty_u < (int32_t)hspwm->ccr_min_limit) duty_u = 0;
    else if (duty_u > (int32_t)hspwm->ccr_max_limit) duty_u = (int32_t)hspwm->ccr_max_limit;
    
    if (duty_v < (int32_t)hspwm->ccr_min_limit) duty_v = 0;
    else if (duty_v > (int32_t)hspwm->ccr_max_limit) duty_v = (int32_t)hspwm->ccr_max_limit;
    
    if (duty_w < (int32_t)hspwm->ccr_min_limit) duty_w = 0;
    else if (duty_w > (int32_t)hspwm->ccr_max_limit) duty_w = (int32_t)hspwm->ccr_max_limit;
    
    // 6. Direct Hardware Register Update (Zero HAL Latency)
    *(hspwm->CCR1_Reg) = (uint32_t)duty_u;
    *(hspwm->CCR2_Reg) = (uint32_t)duty_v;
    *(hspwm->CCR3_Reg) = (uint32_t)duty_w;
}